{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentFormSerialNumber"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkboardingpassdocumentfieldtype\/documentformserialnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkboardingpassdocumentfieldtype\/documentformserialnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBoardingPassDocumentFieldType\/documentFormSerialNumber","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The document form serial number."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentFormSerialNumber"}],"title":"SBSDKBoardingPassDocumentFieldType.documentFormSerialNumber","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBoardingPassDocumentFieldType@SBSDKBoardingPassDocumentFieldTypeDocumentFormSerialNumber","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeDocumentFormSerialNumber"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBoardingPassDocumentFieldType/documentFormSerialNumber":{"role":"symbol","title":"SBSDKBoardingPassDocumentFieldType.documentFormSerialNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentFormSerialNumber"}],"abstract":[{"type":"text","text":"The document form serial number."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBoardingPassDocumentFieldType\/documentFormSerialNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeDocumentFormSerialNumber"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkboardingpassdocumentfieldtype\/documentformserialnumber"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKBoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"The boarding pass field types."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkboardingpassdocumentfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBoardingPassDocumentFieldTypeDocumentFormSerialNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeDocumentFormSerialNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeDocumentFormSerialNumber"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBoardingPassDocumentFieldType~1documentFormSerialNumber\/title","value":"SBSDKBoardingPassDocumentFieldTypeDocumentFormSerialNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBoardingPassDocumentFieldType~1documentFormSerialNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeDocumentFormSerialNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBoardingPassDocumentFieldType\/title","value":"SBSDKBoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}