{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jurisdictionSpecificVehicleClassificationDescription"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkaamvarecordfieldtype\/jurisdictionspecificvehicleclassificationdescription"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkaamvarecordfieldtype\/jurisdictionspecificvehicleclassificationdescription"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAAMVARecordFieldType\/jurisdictionSpecificVehicleClassificationDescription","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The jurisdiction-specific vehicle classification description."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jurisdictionSpecificVehicleClassificationDescription"}],"title":"SBSDKAAMVARecordFieldType.jurisdictionSpecificVehicleClassificationDescription","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAAMVARecordFieldType@SBSDKAAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAAMVARecordFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAAMVARecordFieldType/jurisdictionSpecificVehicleClassificationDescription":{"role":"symbol","title":"SBSDKAAMVARecordFieldType.jurisdictionSpecificVehicleClassificationDescription","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jurisdictionSpecificVehicleClassificationDescription"}],"abstract":[{"type":"text","text":"The jurisdiction-specific vehicle classification description."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAAMVARecordFieldType\/jurisdictionSpecificVehicleClassificationDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaamvarecordfieldtype\/jurisdictionspecificvehicleclassificationdescription"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAAMVARecordFieldType":{"role":"symbol","title":"SBSDKAAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"abstract":[{"type":"text","text":"The known values for AAMVA fields."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaamvarecordfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKAAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAAMVARecordFieldType~1jurisdictionSpecificVehicleClassificationDescription\/title","value":"SBSDKAAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAAMVARecordFieldType~1jurisdictionSpecificVehicleClassificationDescription\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAAMVARecordFieldType\/title","value":"SBSDKAAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}