{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyWords"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/keywords"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/keywords"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/keyWords","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The keywords."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyWords"}],"title":"SBSDKMedicalPlanStandardSubheadingFieldType.keyWords","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalPlanStandardSubheadingFieldType@SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanStandardSubheadingFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanStandardSubheadingFieldType":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document subheading information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanStandardSubheadingFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanstandardsubheadingfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanStandardSubheadingFieldType/keyWords":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingFieldType.keyWords","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyWords"}],"abstract":[{"type":"text","text":"The keywords."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/keyWords","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/keywords"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanStandardSubheadingFieldType\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanStandardSubheadingFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanStandardSubheadingFieldType~1keyWords\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanStandardSubheadingFieldType~1keyWords\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}