{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subheadingFreeText"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/subheadingfreetext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/subheadingfreetext"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/subheadingFreeText","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The free text."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subheadingFreeText"}],"title":"SBSDKMedicalPlanStandardSubheadingFieldType.subheadingFreeText","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalPlanStandardSubheadingFieldType@SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanStandardSubheadingFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanStandardSubheadingFieldType":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document subheading information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanStandardSubheadingFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanstandardsubheadingfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanStandardSubheadingFieldType/subheadingFreeText":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingFieldType.subheadingFreeText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subheadingFreeText"}],"abstract":[{"type":"text","text":"The free text."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/subheadingFreeText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/subheadingfreetext"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanStandardSubheadingFieldType\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanStandardSubheadingFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanStandardSubheadingFieldType~1subheadingFreeText\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanStandardSubheadingFieldType~1subheadingFreeText\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}