{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The ID card field types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"title":"SBSDKIDCardPDF417DocumentFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKIDCardPDF417DocumentFieldType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/birthDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateExpired","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateIssued","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/documentCode","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/firstName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/lastName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/optional1"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/dateExpired":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.dateExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateExpired"}],"abstract":[{"type":"text","text":"The date expired."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/dateexpired"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/documentCode":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.documentCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentCode"}],"abstract":[{"type":"text","text":"The document code."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/documentCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDocumentCode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/documentcode"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/optional1":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.optional1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optional1"}],"abstract":[{"type":"text","text":"The optional one."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/optional1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeOptional1"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/optional1"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/dateIssued":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.dateIssued","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateIssued"}],"abstract":[{"type":"text","text":"The issued date."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateIssued","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/dateissued"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"abstract":[{"type":"text","text":"The ID card field types."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/firstName":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.firstName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"abstract":[{"type":"text","text":"The first name."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/firstName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeFirstName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/firstname"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/lastName":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.lastName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"abstract":[{"type":"text","text":"The last name."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/lastName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeLastName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/lastname"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/birthDate":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.birthDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"}],"abstract":[{"type":"text","text":"The birth date."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/birthDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeBirthDate"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/birthdate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKIDCardPDF417DocumentFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/birthDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateExpired","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateIssued","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/documentCode","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/firstName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/lastName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/optional1"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1dateExpired\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1dateExpired\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1documentCode\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeDocumentCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1documentCode\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDocumentCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1optional1\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeOptional1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1optional1\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeOptional1"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1dateIssued\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1dateIssued\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType\/title","value":"SBSDKIDCardPDF417DocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1firstName\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1firstName\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeFirstName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1lastName\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeLastName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1lastName\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeLastName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1birthDate\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeBirthDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1birthDate\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeBirthDate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}