{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The synchronous functions of this class are running in the same thread that they are called from, so it is up to you to control the concurrency."},{"type":"text","text":" "},{"type":"text","text":"The asynchronous functions run in a shared queue to prevent memory pressure when running multiple extractions at the same time."},{"type":"text","text":" "},{"type":"text","text":"It is recommended to use background queues in most cases."},{"type":"text","text":" "},{"type":"text","text":"Currently the flattening of the PDF document is user’s responsibility. So if the document will have unflattened annotations (except signs), they will not be exported."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Class used to extract pages from a PDF file and returns them in various ways."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"title":"SBSDKPDFPagesExtractor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPDFPagesExtractor","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:compression:outputDirectory:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:outputDirectory:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/images(from:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/images(from:scaling:)"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor/imageURLs(from:scaling:compression:encrypter:outputDirectory:)":{"role":"symbol","title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor/images(from:)":{"role":"symbol","title":"images(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"images"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Extracts pages from PDF and converts them to an array of "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from."},{"type":"text","text":" "},{"type":"text","text":"The scaling of the media box is set to 2."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/images(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imagesFromPDF:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/images(from:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor/imageURLs(from:compression:outputDirectory:)":{"role":"symbol","title":"imageURLs(from:compression:outputDirectory:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."},{"type":"text","text":" "},{"type":"text","text":"No encryption is used here. Media box scale value is 2."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:compression:outputDirectory:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageURLsFromPDF:compression:outputDirectory:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/imageurls(from:compression:outputdirectory:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)":{"role":"symbol","title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKProgress"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL."},{"type":"text","text":" "},{"type":"text","text":"The array of URLs is passed within the completion handler."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:completion:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor":{"role":"symbol","title":"SBSDKPDFPagesExtractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"abstract":[{"type":"text","text":"Class used to extract pages from a PDF file and returns them in various ways."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/init"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor/images(from:scaling:)":{"role":"symbol","title":"images(from:scaling:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"images"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Extracts pages from PDF and converts them to an array of "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/images(from:scaling:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imagesFromPDF:scaling:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/images(from:scaling:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor/imageURLs(from:outputDirectory:)":{"role":"symbol","title":"imageURLs(from:outputDirectory:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."},{"type":"text","text":" "},{"type":"text","text":"No encryption is used here. The compression is set to 0.9. Media box scale value is 2."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:outputDirectory:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageURLsFromPDF:outputDirectory:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/imageurls(from:outputdirectory:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPDFPagesExtractor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:compression:outputDirectory:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:outputDirectory:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/images(from:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/images(from:scaling:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFPagesExtractor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:)\/title","value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1images(from:)\/title","value":"imagesFromPDF:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1images(from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagesFromPDF:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:compression:outputDirectory:)\/title","value":"imageURLsFromPDF:compression:outputDirectory:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:compression:outputDirectory:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsFromPDF:compression:outputDirectory:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)\/title","value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor\/title","value":"SBSDKPDFPagesExtractor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1images(from:scaling:)\/title","value":"imagesFromPDF:scaling:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1images(from:scaling:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagesFromPDF:scaling:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:outputDirectory:)\/title","value":"imageURLsFromPDF:outputDirectory:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:outputDirectory:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsFromPDF:outputDirectory:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}