{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startObserving"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"update"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationState","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKApplicationState","text":"SBSDKApplicationState"},{"kind":"text","text":") -> ())"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstateobserver\/startobserving(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstateobserver\/startobserving(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationStateObserver\/startObserving(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startObserving"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"SBSDKApplicationState","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKApplicationState"},{"kind":"text","text":") -> ())"}],"title":"startObserving(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKApplicationStateObserver(im)startObserving:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"startObserving:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationStateObserver"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKApplicationStateObserver":{"role":"symbol","title":"SBSDKApplicationStateObserver","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationStateObserver"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationStateObserver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationStateObserver"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstateobserver"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKApplicationStateObserver/startObserving(_:)":{"role":"symbol","title":"startObserving(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startObserving"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"SBSDKApplicationState","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKApplicationState"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationStateObserver\/startObserving(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startObserving:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstateobserver\/startobserving(_:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKApplicationState":{"role":"symbol","title":"SBSDKApplicationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationState"}],"abstract":[{"type":"text","text":"An enum describing the current state of the app."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationState"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startObserving:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startObserving:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startObserving:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum SBSDKApplicationState)","preciseIdentifier":"c:BFv(#$@M@ScanbotBarcodeScannerSDK@E@SBSDKApplicationState)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"update"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationStateObserver\/title","value":"SBSDKApplicationStateObserver"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationStateObserver\/fragments","value":[{"kind":"identifier","text":"SBSDKApplicationStateObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationStateObserver~1startObserving(_:)\/title","value":"startObserving:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationStateObserver~1startObserving(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startObserving:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationState\/title","value":"SBSDKApplicationState"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationState\/fragments","value":[{"kind":"identifier","text":"SBSDKApplicationState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}