{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanMedicineSubstanceFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalPlanMedicineSubstanceFieldType","text":"SBSDKMedicalPlanMedicineSubstanceFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanmedicinesubstancefield\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanmedicinesubstancefield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanMedicineSubstanceField\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The field type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalPlanMedicineSubstanceFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalPlanMedicineSubstanceFieldType"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMedicalPlanMedicineSubstanceField(py)type","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanMedicineSubstanceField"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanMedicineSubstanceField":{"role":"symbol","title":"SBSDKMedicalPlanMedicineSubstanceField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanMedicineSubstanceField"}],"abstract":[{"type":"text","text":"The german medical plan document medicine substance information description field."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanMedicineSubstanceField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineSubstanceField"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanmedicinesubstancefield"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanMedicineSubstanceFieldType":{"role":"symbol","title":"SBSDKMedicalPlanMedicineSubstanceFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanMedicineSubstanceFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document medicine substance information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanMedicineSubstanceFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineSubstanceFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanmedicinesubstancefieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanMedicineSubstanceField/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalPlanMedicineSubstanceFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalPlanMedicineSubstanceFieldType"}],"abstract":[{"type":"text","text":"The field type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanMedicineSubstanceField\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplanmedicinesubstancefield\/type"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanMedicineSubstanceFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalPlanMedicineSubstanceFieldType","text":"SBSDKMedicalPlanMedicineSubstanceFieldType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanMedicineSubstanceField\/title","value":"SBSDKMedicalPlanMedicineSubstanceField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanMedicineSubstanceField\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineSubstanceField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanMedicineSubstanceFieldType\/title","value":"SBSDKMedicalPlanMedicineSubstanceFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanMedicineSubstanceFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineSubstanceFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanMedicineSubstanceField~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanMedicineSubstanceField~1type\/fragments","value":[{"kind":"identifier","text":"type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}