{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptionFreeText"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/prescriptionfreetext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/prescriptionfreetext"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/prescriptionFreeText","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The prescription free text."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptionFreeText"}],"title":"SBSDKMedicalPlanSubheadingPrescriptionFieldType.prescriptionFreeText","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalPlanSubheadingPrescriptionFieldType@SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType/prescriptionFreeText":{"role":"symbol","title":"SBSDKMedicalPlanSubheadingPrescriptionFieldType.prescriptionFreeText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptionFreeText"}],"abstract":[{"type":"text","text":"The prescription free text."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/prescriptionFreeText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/prescriptionfreetext"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType":{"role":"symbol","title":"SBSDKMedicalPlanSubheadingPrescriptionFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document subheading prescription information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplansubheadingprescriptionfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType~1prescriptionFreeText\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType~1prescriptionFreeText\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}