{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeCountry"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkswissqrcodefieldtype\/finalpayeecountry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkswissqrcodefieldtype\/finalpayeecountry"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSwissQRCodeFieldType\/finalPayeeCountry","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The final payees country."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeCountry"}],"title":"SBSDKSwissQRCodeFieldType.finalPayeeCountry","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKSwissQRCodeFieldType@SBSDKSwissQRCodeFieldTypeFinalPayeeCountry","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeFinalPayeeCountry"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSwissQRCodeFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSwissQRCodeFieldType/finalPayeeCountry":{"role":"symbol","title":"SBSDKSwissQRCodeFieldType.finalPayeeCountry","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeCountry"}],"abstract":[{"type":"text","text":"The final payees country."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSwissQRCodeFieldType\/finalPayeeCountry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeFinalPayeeCountry"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkswissqrcodefieldtype\/finalpayeecountry"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSwissQRCodeFieldType":{"role":"symbol","title":"SBSDKSwissQRCodeFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSwissQRCodeFieldType"}],"abstract":[{"type":"text","text":"The type of one Swiss QR code field."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSwissQRCodeFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkswissqrcodefieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKSwissQRCodeFieldTypeFinalPayeeCountry"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeFinalPayeeCountry"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeFinalPayeeCountry"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSwissQRCodeFieldType~1finalPayeeCountry\/title","value":"SBSDKSwissQRCodeFieldTypeFinalPayeeCountry"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSwissQRCodeFieldType~1finalPayeeCountry\/fragments","value":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeFinalPayeeCountry"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSwissQRCodeFieldType\/title","value":"SBSDKSwissQRCodeFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSwissQRCodeFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}