{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The SEPA document field types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}],"title":"SBSDKSEPADocumentFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKSEPADocumentFieldType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/amount","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/characterSet","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/identification","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/information","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/purpose","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverBIC","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverIBAN","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/remittance","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/serviceTag","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/version"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/remittance":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.remittance","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remittance"}],"abstract":[{"type":"text","text":"The remittance."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/remittance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeRemittance"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/remittance"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/version":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.version","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"}],"abstract":[{"type":"text","text":"The version."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/version","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeVersion"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/version"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/receiverName":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.receiverName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiverName"}],"abstract":[{"type":"text","text":"The receiver’s name."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/receivername"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/receiverIBAN":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.receiverIBAN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiverIBAN"}],"abstract":[{"type":"text","text":"The receiver’s IBAN."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverIBAN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverIBAN"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/receiveriban"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/characterSet":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.characterSet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"characterSet"}],"abstract":[{"type":"text","text":"The character set."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/characterSet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeCharacterSet"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/characterset"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/serviceTag":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.serviceTag","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceTag"}],"abstract":[{"type":"text","text":"The service tag."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/serviceTag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeServiceTag"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/servicetag"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/receiverBIC":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.receiverBIC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiverBIC"}],"abstract":[{"type":"text","text":"The receiver’s BIC."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverBIC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverBIC"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/receiverbic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType":{"role":"symbol","title":"SBSDKSEPADocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}],"abstract":[{"type":"text","text":"The SEPA document field types."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/purpose":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.purpose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"purpose"}],"abstract":[{"type":"text","text":"The purpose."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/purpose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypePurpose"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/purpose"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/amount":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.amount","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"}],"abstract":[{"type":"text","text":"The amount."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/amount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeAmount"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/amount"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/identification":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.identification","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"identification"}],"abstract":[{"type":"text","text":"The identification."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/identification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeIdentification"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/identification"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSEPADocumentFieldType/information":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.information","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"information"}],"abstract":[{"type":"text","text":"The information."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/information","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeInformation"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksepadocumentfieldtype\/information"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKSEPADocumentFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/amount","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/characterSet","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/identification","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/information","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/purpose","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverBIC","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverIBAN","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/receiverName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/remittance","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/serviceTag","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSEPADocumentFieldType\/version"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1remittance\/title","value":"SBSDKSEPADocumentFieldTypeRemittance"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1remittance\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeRemittance"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1version\/title","value":"SBSDKSEPADocumentFieldTypeVersion"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1version\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1receiverName\/title","value":"SBSDKSEPADocumentFieldTypeReceiverName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1receiverName\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1receiverIBAN\/title","value":"SBSDKSEPADocumentFieldTypeReceiverIBAN"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1receiverIBAN\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverIBAN"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1characterSet\/title","value":"SBSDKSEPADocumentFieldTypeCharacterSet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1characterSet\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeCharacterSet"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1serviceTag\/title","value":"SBSDKSEPADocumentFieldTypeServiceTag"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1serviceTag\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeServiceTag"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1receiverBIC\/title","value":"SBSDKSEPADocumentFieldTypeReceiverBIC"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1receiverBIC\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverBIC"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType\/title","value":"SBSDKSEPADocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1purpose\/title","value":"SBSDKSEPADocumentFieldTypePurpose"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1purpose\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypePurpose"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1amount\/title","value":"SBSDKSEPADocumentFieldTypeAmount"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1amount\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeAmount"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1identification\/title","value":"SBSDKSEPADocumentFieldTypeIdentification"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1identification\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeIdentification"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1information\/title","value":"SBSDKSEPADocumentFieldTypeInformation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSEPADocumentFieldType~1information\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeInformation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}