{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The medical certificate document field types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}],"title":"SBSDKMedicalCertificateDocumentFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalCertificateDocumentFieldType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/accident","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/assignedToAccidentInsuranceDoctor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/birthDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/diagnose","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/diagnosedOn","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/doctorNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/documentDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/firstName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/healthInsuranceNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/incapableOfWorkSince","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/incapableOfWorkUntil","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/initialCertificate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/insuredPersonNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/lastName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/placeOfOperationNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/renewedCertificate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/requiresCare","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/status","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/workAccident"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/placeOfOperationNumber":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.placeOfOperationNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeOfOperationNumber"}],"abstract":[{"type":"text","text":"The place of operation number."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/placeOfOperationNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypePlaceOfOperationNumber"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/placeofoperationnumber"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/initialCertificate":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.initialCertificate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialCertificate"}],"abstract":[{"type":"text","text":"The initial certificate."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/initialCertificate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeInitialCertificate"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/initialcertificate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/doctorNumber":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.doctorNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorNumber"}],"abstract":[{"type":"text","text":"The doctor number."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/doctorNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeDoctorNumber"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/doctornumber"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/insuredPersonNumber":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.insuredPersonNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insuredPersonNumber"}],"abstract":[{"type":"text","text":"The insured person number."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/insuredPersonNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeInsuredPersonNumber"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/insuredpersonnumber"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/diagnose":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.diagnose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"diagnose"}],"abstract":[{"type":"text","text":"The diagnose."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/diagnose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeDiagnose"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/diagnose"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}],"abstract":[{"type":"text","text":"The medical certificate document field types."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/incapableOfWorkUntil":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.incapableOfWorkUntil","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incapableOfWorkUntil"}],"abstract":[{"type":"text","text":"Incapable of work until."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/incapableOfWorkUntil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeIncapableOfWorkUntil"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/incapableofworkuntil"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/incapableOfWorkSince":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.incapableOfWorkSince","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incapableOfWorkSince"}],"abstract":[{"type":"text","text":"Incapable of work since."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/incapableOfWorkSince","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeIncapableOfWorkSince"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/incapableofworksince"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/assignedToAccidentInsuranceDoctor":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.assignedToAccidentInsuranceDoctor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"assignedToAccidentInsuranceDoctor"}],"abstract":[{"type":"text","text":"Assigned to accident insurance doctor."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/assignedToAccidentInsuranceDoctor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/assignedtoaccidentinsurancedoctor"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/diagnosedOn":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.diagnosedOn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"diagnosedOn"}],"abstract":[{"type":"text","text":"Diagnosed on."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/diagnosedOn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeDiagnosedOn"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/diagnosedon"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/documentDate":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.documentDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDate"}],"abstract":[{"type":"text","text":"The document date."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/documentDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeDocumentDate"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/documentdate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/requiresCare":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.requiresCare","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCare"}],"abstract":[{"type":"text","text":"Requires care."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/requiresCare","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeRequiresCare"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/requirescare"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/renewedCertificate":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.renewedCertificate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"renewedCertificate"}],"abstract":[{"type":"text","text":"The renewed certificate."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/renewedCertificate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeRenewedCertificate"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/renewedcertificate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/workAccident":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.workAccident","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"workAccident"}],"abstract":[{"type":"text","text":"The work accident."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/workAccident","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeWorkAccident"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/workaccident"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/healthInsuranceNumber":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.healthInsuranceNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"healthInsuranceNumber"}],"abstract":[{"type":"text","text":"The health insurance number."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/healthInsuranceNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeHealthInsuranceNumber"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/healthinsurancenumber"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/lastName":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.lastName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"abstract":[{"type":"text","text":"The last name."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/lastName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeLastName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/lastname"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/birthDate":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.birthDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"}],"abstract":[{"type":"text","text":"The birth date."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/birthDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeBirthDate"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/birthdate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/accident":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.accident","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accident"}],"abstract":[{"type":"text","text":"The accident."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/accident","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeAccident"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/accident"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/firstName":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.firstName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"abstract":[{"type":"text","text":"The first name."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/firstName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/firstname"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalCertificateDocumentFieldType/status":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.status","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"}],"abstract":[{"type":"text","text":"The status."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/status","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeStatus"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalcertificatedocumentfieldtype\/status"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateDocumentFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/accident","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/assignedToAccidentInsuranceDoctor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/birthDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/diagnose","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/diagnosedOn","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/doctorNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/documentDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/firstName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/healthInsuranceNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/incapableOfWorkSince","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/incapableOfWorkUntil","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/initialCertificate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/insuredPersonNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/lastName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/placeOfOperationNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/renewedCertificate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/requiresCare","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/status","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalCertificateDocumentFieldType\/workAccident"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1placeOfOperationNumber\/title","value":"SBSDKMedicalCertificateDocumentFieldTypePlaceOfOperationNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1placeOfOperationNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypePlaceOfOperationNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1initialCertificate\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeInitialCertificate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1initialCertificate\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeInitialCertificate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1doctorNumber\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeDoctorNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1doctorNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeDoctorNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1insuredPersonNumber\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeInsuredPersonNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1insuredPersonNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeInsuredPersonNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1diagnose\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeDiagnose"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1diagnose\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeDiagnose"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType\/title","value":"SBSDKMedicalCertificateDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1incapableOfWorkUntil\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeIncapableOfWorkUntil"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1incapableOfWorkUntil\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeIncapableOfWorkUntil"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1incapableOfWorkSince\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeIncapableOfWorkSince"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1incapableOfWorkSince\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeIncapableOfWorkSince"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1assignedToAccidentInsuranceDoctor\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1assignedToAccidentInsuranceDoctor\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1diagnosedOn\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeDiagnosedOn"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1diagnosedOn\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeDiagnosedOn"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1documentDate\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeDocumentDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1documentDate\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeDocumentDate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1requiresCare\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeRequiresCare"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1requiresCare\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeRequiresCare"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1renewedCertificate\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeRenewedCertificate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1renewedCertificate\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeRenewedCertificate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1workAccident\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeWorkAccident"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1workAccident\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeWorkAccident"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1healthInsuranceNumber\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeHealthInsuranceNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1healthInsuranceNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeHealthInsuranceNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1lastName\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeLastName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1lastName\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeLastName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1birthDate\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeBirthDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1birthDate\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeBirthDate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1accident\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeAccident"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1accident\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeAccident"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1firstName\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1firstName\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1status\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalCertificateDocumentFieldType~1status\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}