{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderViewDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The delegate protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView"},{"type":"text","text":" class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"title":"SBSDKFinderViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKFinderViewDelegate","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController":{"role":"symbol","title":"SBSDKBarcodeScanAndCountViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."},{"type":"text","text":" "},{"type":"text","text":"Screen also shows snap, scan more and reset buttons."},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"type":"text","text":" "},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"type":"text","text":" "},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"role":"symbol","title":"SBSDKBarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderViewDelegate/finderView(_:didChangeRect:)":{"navigatorTitle":[{"kind":"identifier","text":"finderView:didChangeRect:"}],"role":"symbol","title":"finderView(_:didChangeRect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKFinderView","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKFinderView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs the delegate, that the finder view has changed its finder rectangle."},{"type":"text","text":" "},{"type":"text","text":"Optional."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderviewdelegate\/finderview(_:didchangerect:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView":{"role":"symbol","title":"SBSDKFinderView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderView"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController":{"role":"symbol","title":"SBSDKBaseScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderViewDelegate":{"role":"symbol","title":"SBSDKFinderViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView"},{"type":"text","text":" class."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderviewdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFinderViewDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/title","value":"SBSDKBarcodeScanAndCountViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title","value":"SBSDKBarcodeScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderViewDelegate~1finderView(_:didChangeRect:)\/title","value":"finderView:didChangeRect:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderViewDelegate~1finderView(_:didChangeRect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finderView:didChangeRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/fragments","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderViewDelegate\/title","value":"SBSDKFinderViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderViewDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}