{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The german medical plan document doctor information description field type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"}],"title":"SBSDKMedicalPlanDoctorFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKMedicalPlanDoctorFieldType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/doctorNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/email","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/hospitalID","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/issuerName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/issuingDateAndTime","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/pharmacyID","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/place","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/postalCode","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/street","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/telephoneNumber"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/issuingDateAndTime":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.issuingDateAndTime","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingDateAndTime"}],"abstract":[{"type":"text","text":"The issuing date and time."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/issuingDateAndTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeIssuingDateAndTime"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/issuingdateandtime"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/telephoneNumber":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.telephoneNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"telephoneNumber"}],"abstract":[{"type":"text","text":"The telephone number."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/telephoneNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeTelephoneNumber"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/telephonenumber"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document doctor information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/email":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.email","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"}],"abstract":[{"type":"text","text":"The email."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/email","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeEmail"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/email"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/issuerName":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.issuerName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuerName"}],"abstract":[{"type":"text","text":"The issuer name."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/issuerName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeIssuerName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/issuername"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/doctorNumber":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.doctorNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorNumber"}],"abstract":[{"type":"text","text":"The doctor number."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/doctorNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeDoctorNumber"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/doctornumber"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/pharmacyID":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.pharmacyID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pharmacyID"}],"abstract":[{"type":"text","text":"The pharmacy ID."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/pharmacyID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypePharmacyID"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/pharmacyid"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/hospitalID":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.hospitalID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hospitalID"}],"abstract":[{"type":"text","text":"The hospital ID."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/hospitalID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeHospitalID"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/hospitalid"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/street":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.street","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"street"}],"abstract":[{"type":"text","text":"The street."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/street","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeStreet"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/street"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/postalCode":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.postalCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalCode"}],"abstract":[{"type":"text","text":"The postal code."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/postalCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypePostalCode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/postalcode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMedicalPlanDoctorFieldType/place":{"role":"symbol","title":"SBSDKMedicalPlanDoctorFieldType.place","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"place"}],"abstract":[{"type":"text","text":"The place."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/place","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypePlace"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmedicalplandoctorfieldtype\/place"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalPlanDoctorFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/doctorNumber","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/email","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/hospitalID","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/issuerName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/issuingDateAndTime","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/pharmacyID","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/place","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/postalCode","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/street","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMedicalPlanDoctorFieldType\/telephoneNumber"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1issuingDateAndTime\/title","value":"SBSDKMedicalPlanDoctorFieldTypeIssuingDateAndTime"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1issuingDateAndTime\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeIssuingDateAndTime"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1telephoneNumber\/title","value":"SBSDKMedicalPlanDoctorFieldTypeTelephoneNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1telephoneNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeTelephoneNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType\/title","value":"SBSDKMedicalPlanDoctorFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1email\/title","value":"SBSDKMedicalPlanDoctorFieldTypeEmail"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1email\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1issuerName\/title","value":"SBSDKMedicalPlanDoctorFieldTypeIssuerName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1issuerName\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeIssuerName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1doctorNumber\/title","value":"SBSDKMedicalPlanDoctorFieldTypeDoctorNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1doctorNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeDoctorNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1pharmacyID\/title","value":"SBSDKMedicalPlanDoctorFieldTypePharmacyID"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1pharmacyID\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypePharmacyID"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1hospitalID\/title","value":"SBSDKMedicalPlanDoctorFieldTypeHospitalID"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1hospitalID\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeHospitalID"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1street\/title","value":"SBSDKMedicalPlanDoctorFieldTypeStreet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1street\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypeStreet"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1postalCode\/title","value":"SBSDKMedicalPlanDoctorFieldTypePostalCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1postalCode\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypePostalCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1place\/title","value":"SBSDKMedicalPlanDoctorFieldTypePlace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMedicalPlanDoctorFieldType~1place\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanDoctorFieldTypePlace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}