{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1SystemElementValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1SystemElementValidationStatus","text":"SBSDKGS1SystemElementValidationStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1documentfield\/validationstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1documentfield\/validationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1DocumentField\/validationStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contains the parse error, if any was found during the parsing."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGS1SystemElementValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1SystemElementValidationStatus"}],"title":"validationStatus","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGS1DocumentField(py)validationStatus","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"validationStatus"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1DocumentField"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1DocumentField":{"role":"symbol","title":"SBSDKGS1DocumentField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1DocumentField"}],"abstract":[{"type":"text","text":"A class describing a data field of a GS1 code."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1DocumentField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1DocumentField"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1documentfield"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1SystemElementValidationStatus":{"role":"symbol","title":"SBSDKGS1SystemElementValidationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1SystemElementValidationStatus"}],"abstract":[{"type":"text","text":"A GS1 document field validation status."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1SystemElementValidationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1SystemElementValidationStatus"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1systemelementvalidationstatus"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1DocumentField/validationStatus":{"role":"symbol","title":"validationStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGS1SystemElementValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1SystemElementValidationStatus"}],"abstract":[{"type":"text","text":"Contains the parse error, if any was found during the parsing."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1DocumentField\/validationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validationStatus"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1documentfield\/validationstatus"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"validationStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"validationStatus"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1SystemElementValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1SystemElementValidationStatus","text":"SBSDKGS1SystemElementValidationStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationStatus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1DocumentField\/title","value":"SBSDKGS1DocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1DocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1DocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1SystemElementValidationStatus\/title","value":"SBSDKGS1SystemElementValidationStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1SystemElementValidationStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1SystemElementValidationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1DocumentField~1validationStatus\/title","value":"validationStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1DocumentField~1validationStatus\/fragments","value":[{"kind":"identifier","text":"validationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}