{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compartmentCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkboardingpassdocumentfieldtype\/compartmentcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkboardingpassdocumentfieldtype\/compartmentcode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBoardingPassDocumentFieldType\/compartmentCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The compartment code."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compartmentCode"}],"title":"SBSDKBoardingPassDocumentFieldType.compartmentCode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBoardingPassDocumentFieldType@SBSDKBoardingPassDocumentFieldTypeCompartmentCode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCompartmentCode"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKBoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"The boarding pass field types."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkboardingpassdocumentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBoardingPassDocumentFieldType/compartmentCode":{"role":"symbol","title":"SBSDKBoardingPassDocumentFieldType.compartmentCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compartmentCode"}],"abstract":[{"type":"text","text":"The compartment code."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBoardingPassDocumentFieldType\/compartmentCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCompartmentCode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkboardingpassdocumentfieldtype\/compartmentcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBoardingPassDocumentFieldTypeCompartmentCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCompartmentCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCompartmentCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBoardingPassDocumentFieldType\/title","value":"SBSDKBoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBoardingPassDocumentFieldType~1compartmentCode\/title","value":"SBSDKBoardingPassDocumentFieldTypeCompartmentCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBoardingPassDocumentFieldType~1compartmentCode\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCompartmentCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}