{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateExpired"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/dateexpired"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/dateexpired"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateExpired","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The date expired."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateExpired"}],"title":"SBSDKIDCardPDF417DocumentFieldType.dateExpired","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKIDCardPDF417DocumentFieldType@SBSDKIDCardPDF417DocumentFieldTypeDateExpired","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"abstract":[{"type":"text","text":"The ID card field types."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/dateExpired":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.dateExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateExpired"}],"abstract":[{"type":"text","text":"The date expired."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/dateexpired"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType\/title","value":"SBSDKIDCardPDF417DocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1dateExpired\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1dateExpired\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateExpired"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}