{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateIssued"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/dateissued"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/dateissued"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateIssued","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The issued date."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateIssued"}],"title":"SBSDKIDCardPDF417DocumentFieldType.dateIssued","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKIDCardPDF417DocumentFieldType@SBSDKIDCardPDF417DocumentFieldTypeDateIssued","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"abstract":[{"type":"text","text":"The ID card field types."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIDCardPDF417DocumentFieldType/dateIssued":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.dateIssued","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateIssued"}],"abstract":[{"type":"text","text":"The issued date."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIDCardPDF417DocumentFieldType\/dateIssued","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkidcardpdf417documentfieldtype\/dateissued"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType\/title","value":"SBSDKIDCardPDF417DocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1dateIssued\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIDCardPDF417DocumentFieldType~1dateIssued\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeDateIssued"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}