{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarCodeScannerDocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarCodeScannerDocumentFormat","text":"SBSDKBarCodeScannerDocumentFormat"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"inputString","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The string to be parsed."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"barcode document or nil."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentparser\/parsedocument(inputstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentparser\/parsedocument(inputstring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentParser\/parseDocument(inputString:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parses the string into one of the supported document type or returns nil if none of the supported document types was detected."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKBarCodeScannerDocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarCodeScannerDocumentFormat"},{"kind":"text","text":"?"}],"title":"parseDocument(inputString:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentParser(im)parseDocumentWithInputString:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"parseDocumentWithInputString:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentParser"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentParser":{"role":"symbol","title":"SBSDKBarcodeDocumentParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentParser"}],"abstract":[{"type":"text","text":"A class to parse a raw string value (usually taken from the barcode) into a formatted document of the supported type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentParser"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentparser"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarCodeScannerDocumentFormat":{"role":"symbol","title":"SBSDKBarCodeScannerDocumentFormat","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}],"abstract":[{"type":"text","text":"Base class for describing recognized and parsed barcode information."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarCodeScannerDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerdocumentformat"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentParser/parseDocument(inputString:)":{"role":"symbol","title":"parseDocument(inputString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKBarCodeScannerDocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarCodeScannerDocumentFormat"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Parses the string into one of the supported document type or returns nil if none of the supported document types was detected."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentParser\/parseDocument(inputString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseDocumentWithInputString:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentparser\/parsedocument(inputstring:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"parseDocumentWithInputString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseDocumentWithInputString:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<SBSDKBarCodeScannerDocumentFormat>","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarCodeScannerDocumentFormat"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"parseDocumentWithInputString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"inputString"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentParser\/title","value":"SBSDKBarcodeDocumentParser"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentParser\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentParser"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarCodeScannerDocumentFormat\/title","value":"SBSDKBarCodeScannerDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarCodeScannerDocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentParser~1parseDocument(inputString:)\/title","value":"parseDocumentWithInputString:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentParser~1parseDocument(inputString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseDocumentWithInputString:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}